defaults:
  - preprocessing: rubert_minimal
  - training: rubert
  - model: rubert
  - _self_


small_classes: ["Качество материалов", "Интерфейс платформы", "Общение с куратором"]
test_size: 0.2


preprocessing:
  max_length: 256
